apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sshintern-conf3
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "158.3.0.0/24",
        "rangeStart": "158.3.0.0",  
        "rangeEnd": "158.3.0.50",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "158.3.0.1"
      }
    }'