apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: nad-static-ip
spec:
  config: '{
        "cniVersion": "0.3.1",
                "name": "bridge",
                "type": "bridge",
                "bridge": "b1",
                "ipMasq": false,
                "ipam": {
                        "type": "staticss",
                        "allocations": [
                                          {"namespace": "default", "pod": "mi3-fifa1-pod", "address": "10.0.2.40/24"},
                                          {"namespace": "example", "pod": "ex-1", "address": "10.0.2.41/24"},
                                          {"namespace": "example", "pod": "ex-2", "address": "10.0.2.42/24"},
                                          {"namespace": "example", "pod": "ex-3", "address": "10.0.2.43/24"},
                                          {"namespace": "example", "pod": "ex-4", "address": "10.0.2.44/24"}
                                       ]
                }
        }'