## --- Beginning of YAML file ---
## 1. Tell Kubernetes which API version to use
apiVersion: v1
## 2. Declare what kind of resource we want to create
kind: Pod
## 3. Set metadata for this resource
metadata:
  name: mi4-s3-pod ## Name of the Pod
  labels: ## Labels help us find and organize Pods
    app: mi4-s3
  annotations:
    k8s.v1.cni.cncf.io/networks: static-ip-s3, sshintern-conf3 # , bridge-s3-fifa-conf, bridge-s3-uefa-conf, bridge-s3-fifa-conf bridge-s3-s1, bridge-s3-s2,
## 4. Define what the Pod should contain
spec:
  containers: ## Pod can run one or more containers
    - name: mi4-s3
      image: docker.io/miniinterneteth/d_switch:latest
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]
      ports: 
        - containerPort: 22
