#@ load("@ytt:data", "data")

#@ def name():
#@   return "missh-"+data.values.as5.name 
#@ end

#@ def labels():
app: #@ name()
#@ end


apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ name()
  labels: #@ labels()
  namespace: #@ data.values.as5.name 
spec:
  replicas: 1
  selector:
    matchLabels: #@ labels() 
  template:
    metadata:
     name: #@ name()
     labels: #@ labels()
     annotations:
        k8s.v1.cni.cncf.io/networks: 
        'cni.projectcalico.org/ipAddrs': #@ "[\"" + data.values.as5.ipaddressprefix + "0.2\"]"
    spec:
      containers: 
        - name: #@ name() + "-pod" 
          image: docker.io/miniinterneteth/d_ssh:latest
          ports:
          - containerPort: 22
          volumeMounts:
          - mountPath: /root
            name: example-volume
      volumes:
      - name: example-volume
    hostPath:
      path: /home/adrian/miniinternetk8/beispielsetup/groups
      
#@ if/end data.values.service.enabled:
---
apiVersion: v1
kind: Service
metadata:
  name: #@ name()
  namespace: #@ data.values.as5.name 
spec:
  selector: #@ labels()
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: NodePort
    
