## --- Beginning of YAML file ---
## 1. Tell Kubernetes which API version to use
apiVersion: v1
## 2. Declare what kind of resource we want to create
kind: Pod
## 3. Set metadata for this resource
metadata:
  name: mi3-fifa1-pod ## Name of the Pod
  labels: ## Labels help us find and organize Pods
    app: mi3-fifa1
  annotations:
    k8s.v1.cni.cncf.io/networks: sshintern-conf3@ssh, bridge-s1-fifa-conf@s1  
## 4. Define what the Pod should contain
spec:
  containers: ## Pod can run one or more containers
    - name: mi3-fifa1
      image: docker.io/miniinterneteth/d_host:latest
      ports: 
        - containerPort: 22
      volumeMounts:
      - mountPath: /root/.ssh
        name: example-volume
  volumes:
  - name: example-volume
    # mount /data/foo, but only if that directory already exists
    hostPath:
      path: /home/adrian/ # directory location on host
      
      
