## --- Beginning of YAML file ---
## 1. Tell Kubernetes which API version to use
apiVersion: v1
## 2. Declare what kind of resource we want to create
kind: Pod
## 3. Set metadata for this resource
metadata:
  name: mi3-s2-pod ## Name of the Pod
  labels: ## Labels help us find and organize Pods
    app: mi3-s2
  annotations:
    k8s.v1.cni.cncf.io/networks: bridge-s2-fifa-conf@fifa2, bridge-s2-uefa-conf@uefa2, bridge-s2-s1-conf@s1, bridge-s2-s3-conf@s3, bridge-s2-base-conf@base
    'cni.projectcalico.org/ipAddrs': '["158.3.100.4"]'
## 4. Define what the Pod should contain
spec:
  containers: ## Pod can run one or more containers
    - name: mi3-s2
      image: docker.io/miniinterneteth/d_switch:latest
      ports: 
        - containerPort: 22
      volumeMounts:
      - mountPath: /root
        name: example-volume
  volumes:
  - name: example-volume
    # mount /data/foo, but only if that directory already exists
    hostPath:
      path: /home/adrian/miniinternetk8/beispielsetup/groups/g3