apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: missh3
  name: missh3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: missh3
  template:
    metadata:
      name: missh3
      labels:
        app: missh3
      annotations:
        k8s.v1.cni.cncf.io/networks:
        'cni.projectcalico.org/ipAddrs': '["158.3.0.2"]'
    spec:
      containers: ## Pod can run one or more containers
        - name: missh3 ## Name of the container
          image: docker.io/miniinterneteth/d_ssh:latest ## Which container image to use
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports: ## Which ports to expose
          - containerPort: 22
          volumeMounts:
          - mountPath: /root
            name: example-volume
      volumes:
      - name: example-volume
    # mount /data/foo, but only if that directory already exists
    hostPath:
      path: /home/adrian/miniinternetk8/beispielsetup/groups
---

apiVersion: v1
kind: Service
metadata:
  name: missh3
spec:
  selector:
    app: missh3
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 32003
  type: NodePort