## --- Beginning of YAML file ---
## 1. Tell Kubernetes which API version to use
apiVersion: v1
## 2. Declare what kind of resource we want to create
kind: Pod
## 3. Set metadata for this resource
metadata:
  name: mi3-zuri-pod ## Name of the Pod
  labels: ## Labels help us find and organize Pods
    app: mi3-zuri
  annotations:
    k8s.v1.cni.cncf.io/networks: bridge-s1-zuri-conf@s2, bridge-base-zuri-conf@zuri, bridge-zuri-gene-conf@gene
    'cni.projectcalico.org/ipAddrs': '["158.3.10.1"]'
## 4. Define what the Pod should contain
spec:
  containers: ## Pod can run one or more containers
    - name: mi3-zuri
      image: docker.io/miniinterneteth/d_router:latest
      ports: 
        - containerPort: 22
      volumeMounts:
      - mountPath: /root
        name: example-volume
  volumes:
  - name: example-volume
    # mount /data/foo, but only if that directory already exists
    hostPath:
      path: /home/adrian/miniinternetk8/beispielsetup/groups/g3